---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Apache-Test
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '2.06'
  File::Spec: '0.8'
version: '1.40'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
