#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Test
version:      1.07
version_from: 
installdirs:  site
requires:
    File::Spec:                    0.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
