#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Test
version:      1.03-dev
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
